### ISSUE TITLE
Atom 1.13 Shadow DOM removal

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-syntax#15]
Starting from Atom version 1.13, the contents of `atom-text-editor` [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html).
This means the `:host` and `::shadow` pseudo-selectors should be completely removed and all syntax selectors should be prepended with `syntax--`.
To prevent breakage with existing style sheets, Atom will automatically upgrade selectors for versions less or equal to 1.12.

**Tasks**
  - [x] Remove all `:host` and `::shadow` pseudo-selectors
  - [x] Prepend all syntax selectors with `syntax--`
  - [x] Update `package.json` minimal Atom engine version to `>=1.13.0`

**Comment by arcticicestudio** [comment]
🚢 Shipped in apm package release version 🏷 [2.1.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.1.0)!
