### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-syntax#5]
:atom: 📦 ❤️ 
This epic tracks issues for optimized support implementations of the most popular Atom language packages.
I'm happy for any help and improvement suggestions, please feel free to create a PR or report issues.
## 💬 Community
- [x] <img src="https://avatars1.githubusercontent.com/u/2313237" width=16 height=16/>  [`language-babel`](https://atom.io/packages/language-babel) by [gandm](https://github.com/gandm) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
  - [ES2016](https://babeljs.io)
  - [ESNext](https://github.com/esnext/esnext)
  - <img src="https://atom.io/favicon.ico" width=16 height=16/> Atom's [Etch](https://github.com/atom/etch)
  - <img src="https://facebook.com/favicon.ico" width=16 height=16/> Facebook's <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React](https://facebook.github.io/react), <img src="https://flowtype.org/static/favicon.png" width=16 height=16/> [Flow](https://flowtype.org) and <img src="http://graphql.org/img/favicon.png" width=16 height=16/> [GraphQL](http://graphql.org)
- [x] <img src="https://avatars0.githubusercontent.com/u/1481354" width=16 height=16/>  [`language-elixir`](https://atom.io/packages/language-elixir) by [elixir-lang](https://github.com/elixir-lang) (@arcticicestudio, #14 , 429a321f)
- [ ] <img src="https://avatars2.githubusercontent.com/u/529516" width=16 height=16/>  [`language-diff`](https://atom.io/packages/language-diff) by [miketheman](https://github.com/miketheman)
- [x] <img src="https://avatars3.githubusercontent.com/u/569817" width=16 height=16/>  [`language-glsl`](https://atom.io/packages/language-glsl) by [hughsk](https://github.com/hughsk) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] <img src="https://avatars0.githubusercontent.com/u/6979737" width=16 height=16/>  [`language-haml`](https://atom.io/packages/language-haml) by [ezekg](https://github.com/ezekg) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] <img src="https://avatars3.githubusercontent.com/u/12533767" width=16 height=16/>  [`language-haskell`](https://atom.io/packages/language-haskell) by [atom-haskell](https://github.com/atom-haskell) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] <img src="https://avatars2.githubusercontent.com/u/743164" width=16 height=16/> [`language-julia`](https://atom.io/packages/language-julia) by [JuliaLang](https://github.com/JuliaLang) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
## ⚛️  Core
- [x] [`language-c`](https://atom.io/packages/language-c) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-clojure`](https://atom.io/packages/language-clojure) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-coffee-script`](https://atom.io/packages/language-coffee-script) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-csharp`](https://atom.io/packages/language-csharp) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-css`](https://atom.io/packages/language-css) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-gfm`](https://atom.io/packages/language-gfm) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-go`](https://atom.io/packages/language-go) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-java`](https://atom.io/packages/language-java) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
  - Includes the `.source.java-properties` CSS class scope
- [x] [`language-javascript`](https://atom.io/packages/language-javascript) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-json`](https://atom.io/packages/language-json) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-less`](https://atom.io/packages/language-less) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-php`](https://atom.io/packages/language-php) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-python`](https://atom.io/packages/language-python) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-ruby`](https://atom.io/packages/language-ruby) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-sass`](https://atom.io/packages/language-sass) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-scala`](https://atom.io/packages/language-scala) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-shellscript`](https://atom.io/packages/language-shellscript) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-yaml`](https://atom.io/packages/language-yaml) (@arcticicestudio, #8 PR #12) :package: :label: [2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v2.0.0)
- [x] [`language-xml`](https://atom.io/packages/language-xml) (@arcticicestudio, #13 , fd455260)

---

📦 Released APM package
🏷 Version tag

**Comment by arcticicestudio** [comment]
Added <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React.js](https://atom.io/packages/react) (`.jsx`) to the list.

**Comment by arcticicestudio** [comment]
:heavy_check_mark: Completed <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React.js](https://atom.io/packages/react) (`.jsx`)
Version: [`v0.18.0`](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v0.18.0)
GitHub Issue: @Pszek, [GHI #3](https://github.com/arcticicestudio/northem-light-atom-syntax/issues/3)

**Comment by arcticicestudio** [comment]
Added <img src="http://www.latex-project.org/favicon.ico" width=16 height=16/> [LaTeX](https://atom.io/packages/language-latex)(`.tex`,`.bib`, `.bbx`, `.cbx`, `.sty`) to the list.
This is a request I've received via :email: email.

**Comment by arcticicestudio** [comment]
Resolved tasks:

### 💬 Community
<img src="https://avatars0.githubusercontent.com/u/1481354" width=16 height=16/>  [`language-elixir`](https://atom.io/packages/language-elixir)

### :atom: Core
[`language-xml`](https://atom.io/packages/language-xml)
